set(CMAKE_SYSTEM_NAME ${CMAKE_HOST_SYSTEM_NAME})
set(CMAKE_SYSTEM_PROCESSOR ${CMAKE_HOST_SYSTEM_PROCESSOR})
set(CMAKE_SYSTEM_VERSION ${CMAKE_HOST_SYSTEM_VERSION})

set(CMAKE_C_COMPILER gcc CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER g++ CACHE FILEPATH "")